import pytest
from main import MainApp

def test_app_multiply_command(capfd, monkeypatch):
    """Test that the REPL correctly handles the 'multiply' command and outputs the expected result."""
    inputs = iter(['multiply 2 1', 'exit'])
    monkeypatch.setattr('builtins.input', lambda _: next(inputs))

    app = MainApp()
    
    with pytest.raises(SystemExit) as exit_info:
        app.load_plugins()
        app.start()
    
    assert exit_info.value.code == 0, "The app did not exit as expected"
    
    # Capture the output generated by the command
    output, _ = capfd.readouterr()
    
    assert "2" in output, "The 'multiply' command did not produce the expected output."
